In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
#dg will be the dhortform of diagnosis
#cd is for the code column
dg = pd.read_excel(r"C:\Users\user\Downloads\Data Sample.xlsx", sheet_name="edited_data")
cd = pd.read_excel(r"C:\Users\user\Downloads\Data Sample.xlsx", sheet_name="testcodes")

In [4]:
dg = dg.copy()
cd = cd.copy()

In [5]:
dg.columns

Index(['DocumentNo', 'final_encounter_nr', 'diagnosis1', 'diagnosis2',
       'diagnosis3', 'diagnosis4', 'diagnosis5', 'diagnosis6', 'diagnosis7',
       'diagnosis8', 'diagnosis9', 'diagnosis1a', 'Location', 'Service',
       'ConsultingDoctor', 'ItemName', 'TotalAmount', 'modify_id', 'create_id',
       'ChargeDate'],
      dtype='object')

In [6]:
list(cd.columns)

['ICD10_Code', 'WHO Full Description']

In [7]:
dg_desc = dg.copy()
dig_col = ['diagnosis1', 'diagnosis2','diagnosis3', 'diagnosis4', 'diagnosis5', 'diagnosis6', 'diagnosis7','diagnosis8', 'diagnosis9', 'diagnosis1a']
for col in dig_col:
    dg_desc = dg_desc.merge(cd,left_on=col,right_on='ICD10_Code',how="left")
    dg_desc=dg_desc.rename(columns={'WHO Full Description':f"{col}_desc"})
    dg_desc=dg_desc.drop(columns=['ICD10_Code'])

In [8]:
dg_desc

,DocumentNo,final_encounter_nr,diagnosis1,diagnosis2,diagnosis3,diagnosis4,diagnosis5,diagnosis6,diagnosis7,diagnosis8,...,diagnosis1_desc,diagnosis2_desc,diagnosis3_desc,diagnosis4_desc,diagnosis5_desc,diagnosis6_desc,diagnosis7_desc,diagnosis8_desc,diagnosis9_desc,diagnosis1a_desc
0,MHOPB061261364/25,1.018012e+11,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,MHOPB031193989/25,1.022121e+11,V49.5,R07.4,R10.3,NaN,NaN,NaN,NaN,NaN,...,Passenger of car injured in collision with oth...,"Chest pain, unspecified",Pain localised to other parts of lower abdomen,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,MHOPB031193989/25,1.022121e+11,V49.5,R07.4,R10.3,NaN,NaN,NaN,NaN,NaN,...,Passenger of car injured in collision with oth...,"Chest pain, unspecified",Pain localised to other parts of lower abdomen,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MHOPB031193989/25,1.022121e+11,V49.5,R07.4,R10.3,NaN,NaN,NaN,NaN,NaN,...,Passenger of car injured in collision with oth...,"Chest pain, unspecified",Pain localised to other parts of lower abdomen,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MHOPB031193989/25,1.022121e+11,V49.5,R07.4,R10.3,NaN,NaN,NaN,NaN,NaN,...,Passenger of car injured in collision with oth...,"Chest pain, unspecified",Pain localised to other parts of lower abdomen,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771264,WAOPB06156271/25,1.225063e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
771265,WAOPB06156309/25,1.225063e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
771266,WAOPB06156316/25,1.225063e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
771267,WAOPB06156336/25,1.225063e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
771268,WAOPB06156346/25,1.225063e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
dg_desc.columns

Index(['DocumentNo', 'final_encounter_nr', 'diagnosis1', 'diagnosis2',
       'diagnosis3', 'diagnosis4', 'diagnosis5', 'diagnosis6', 'diagnosis7',
       'diagnosis8', 'diagnosis9', 'diagnosis1a', 'Location', 'Service',
       'ConsultingDoctor', 'ItemName', 'TotalAmount', 'modify_id', 'create_id',
       'ChargeDate', 'diagnosis1_desc', 'diagnosis2_desc', 'diagnosis3_desc',
       'diagnosis4_desc', 'diagnosis5_desc', 'diagnosis6_desc',
       'diagnosis7_desc', 'diagnosis8_desc', 'diagnosis9_desc',
       'diagnosis1a_desc'],
      dtype='object')

In [10]:
#We are combining the text and not including nulls in our combined text
description = ['diagnosis1_desc', 'diagnosis2_desc', 'diagnosis3_desc','diagnosis4_desc', 'diagnosis5_desc', 'diagnosis6_desc','diagnosis7_desc', 'diagnosis8_desc', 'diagnosis9_desc','diagnosis1a_desc']
dg_desc["DSCPT"] = dg_desc[description].agg(lambda x:",".join([str(i) for i in x if pd.notnull(i)]), axis=1)

In [11]:
dg_desc

,DocumentNo,final_encounter_nr,diagnosis1,diagnosis2,diagnosis3,diagnosis4,diagnosis5,diagnosis6,diagnosis7,diagnosis8,...,diagnosis2_desc,diagnosis3_desc,diagnosis4_desc,diagnosis5_desc,diagnosis6_desc,diagnosis7_desc,diagnosis8_desc,diagnosis9_desc,diagnosis1a_desc,DSCPT
0,MHOPB061261364/25,1.018012e+11,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
1,MHOPB031193989/25,1.022121e+11,V49.5,R07.4,R10.3,NaN,NaN,NaN,NaN,NaN,...,"Chest pain, unspecified",Pain localised to other parts of lower abdomen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Passenger of car injured in collision with oth...
2,MHOPB031193989/25,1.022121e+11,V49.5,R07.4,R10.3,NaN,NaN,NaN,NaN,NaN,...,"Chest pain, unspecified",Pain localised to other parts of lower abdomen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Passenger of car injured in collision with oth...
3,MHOPB031193989/25,1.022121e+11,V49.5,R07.4,R10.3,NaN,NaN,NaN,NaN,NaN,...,"Chest pain, unspecified",Pain localised to other parts of lower abdomen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Passenger of car injured in collision with oth...
4,MHOPB031193989/25,1.022121e+11,V49.5,R07.4,R10.3,NaN,NaN,NaN,NaN,NaN,...,"Chest pain, unspecified",Pain localised to other parts of lower abdomen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Passenger of car injured in collision with oth...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771264,WAOPB06156271/25,1.225063e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
771265,WAOPB06156309/25,1.225063e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
771266,WAOPB06156316/25,1.225063e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
771267,WAOPB06156336/25,1.225063e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
771268,WAOPB06156346/25,1.225063e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [12]:
diagnosis = ['diagnosis1', 'diagnosis2','diagnosis3', 'diagnosis4', 'diagnosis5', 'diagnosis6', 'diagnosis7','diagnosis8', 'diagnosis9', 'diagnosis1a']
dg_desc["Diagnosis"] = dg_desc[diagnosis].agg(lambda x: "-".join([str(i) for i in x if pd.notnull(i)]), axis=1)

In [13]:
dg_desc

,DocumentNo,final_encounter_nr,diagnosis1,diagnosis2,diagnosis3,diagnosis4,diagnosis5,diagnosis6,diagnosis7,diagnosis8,...,diagnosis3_desc,diagnosis4_desc,diagnosis5_desc,diagnosis6_desc,diagnosis7_desc,diagnosis8_desc,diagnosis9_desc,diagnosis1a_desc,DSCPT,Diagnosis
0,MHOPB061261364/25,1.018012e+11,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0
1,MHOPB031193989/25,1.022121e+11,V49.5,R07.4,R10.3,NaN,NaN,NaN,NaN,NaN,...,Pain localised to other parts of lower abdomen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Passenger of car injured in collision with oth...,V49.5-R07.4-R10.3
2,MHOPB031193989/25,1.022121e+11,V49.5,R07.4,R10.3,NaN,NaN,NaN,NaN,NaN,...,Pain localised to other parts of lower abdomen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Passenger of car injured in collision with oth...,V49.5-R07.4-R10.3
3,MHOPB031193989/25,1.022121e+11,V49.5,R07.4,R10.3,NaN,NaN,NaN,NaN,NaN,...,Pain localised to other parts of lower abdomen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Passenger of car injured in collision with oth...,V49.5-R07.4-R10.3
4,MHOPB031193989/25,1.022121e+11,V49.5,R07.4,R10.3,NaN,NaN,NaN,NaN,NaN,...,Pain localised to other parts of lower abdomen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Passenger of car injured in collision with oth...,V49.5-R07.4-R10.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771264,WAOPB06156271/25,1.225063e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,
771265,WAOPB06156309/25,1.225063e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,
771266,WAOPB06156316/25,1.225063e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,
771267,WAOPB06156336/25,1.225063e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,
771268,WAOPB06156346/25,1.225063e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,

In [14]:
diagnosis = ['diagnosis1', 'diagnosis2','diagnosis3', 'diagnosis4', 'diagnosis5', 'diagnosis6', 'diagnosis7','diagnosis8', 'diagnosis9', 'diagnosis1a']
dg_desc["Orig_diag"] = dg_desc[diagnosis].agg(lambda x: ",".join([str(i) for i in x if pd.notnull(i)]), axis=1)

In [15]:
dg_desc

,DocumentNo,final_encounter_nr,diagnosis1,diagnosis2,diagnosis3,diagnosis4,diagnosis5,diagnosis6,diagnosis7,diagnosis8,...,diagnosis4_desc,diagnosis5_desc,diagnosis6_desc,diagnosis7_desc,diagnosis8_desc,diagnosis9_desc,diagnosis1a_desc,DSCPT,Diagnosis,Orig_diag
0,MHOPB061261364/25,1.018012e+11,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0,0
1,MHOPB031193989/25,1.022121e+11,V49.5,R07.4,R10.3,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Passenger of car injured in collision with oth...,V49.5-R07.4-R10.3,"V49.5,R07.4,R10.3"
2,MHOPB031193989/25,1.022121e+11,V49.5,R07.4,R10.3,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Passenger of car injured in collision with oth...,V49.5-R07.4-R10.3,"V49.5,R07.4,R10.3"
3,MHOPB031193989/25,1.022121e+11,V49.5,R07.4,R10.3,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Passenger of car injured in collision with oth...,V49.5-R07.4-R10.3,"V49.5,R07.4,R10.3"
4,MHOPB031193989/25,1.022121e+11,V49.5,R07.4,R10.3,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Passenger of car injured in collision with oth...,V49.5-R07.4-R10.3,"V49.5,R07.4,R10.3"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771264,WAOPB06156271/25,1.225063e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,
771265,WAOPB06156309/25,1.225063e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,
771266,WAOPB06156316/25,1.225063e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,
771267,WAOPB06156336/25,1.225063e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,
771268,WAOPB06156346/25,1.225063e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,

In [16]:
dg_desc["final_encounter_nr"] = dg_desc["final_encounter_nr"].astype("Int64").astype(str)

In [17]:
dg_desc

,DocumentNo,final_encounter_nr,diagnosis1,diagnosis2,diagnosis3,diagnosis4,diagnosis5,diagnosis6,diagnosis7,diagnosis8,...,diagnosis4_desc,diagnosis5_desc,diagnosis6_desc,diagnosis7_desc,diagnosis8_desc,diagnosis9_desc,diagnosis1a_desc,DSCPT,Diagnosis,Orig_diag
0,MHOPB061261364/25,101801231033,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0,0
1,MHOPB031193989/25,102212104011,V49.5,R07.4,R10.3,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Passenger of car injured in collision with oth...,V49.5-R07.4-R10.3,"V49.5,R07.4,R10.3"
2,MHOPB031193989/25,102212104011,V49.5,R07.4,R10.3,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Passenger of car injured in collision with oth...,V49.5-R07.4-R10.3,"V49.5,R07.4,R10.3"
3,MHOPB031193989/25,102212104011,V49.5,R07.4,R10.3,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Passenger of car injured in collision with oth...,V49.5-R07.4-R10.3,"V49.5,R07.4,R10.3"
4,MHOPB031193989/25,102212104011,V49.5,R07.4,R10.3,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Passenger of car injured in collision with oth...,V49.5-R07.4-R10.3,"V49.5,R07.4,R10.3"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771264,WAOPB06156271/25,122506301004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,
771265,WAOPB06156309/25,122506301017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,
771266,WAOPB06156316/25,122506304039,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,
771267,WAOPB06156336/25,122506301022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,
771268,WAOPB06156346/25,122506301027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,

In [18]:
dg_desc.columns

Index(['DocumentNo', 'final_encounter_nr', 'diagnosis1', 'diagnosis2',
       'diagnosis3', 'diagnosis4', 'diagnosis5', 'diagnosis6', 'diagnosis7',
       'diagnosis8', 'diagnosis9', 'diagnosis1a', 'Location', 'Service',
       'ConsultingDoctor', 'ItemName', 'TotalAmount', 'modify_id', 'create_id',
       'ChargeDate', 'diagnosis1_desc', 'diagnosis2_desc', 'diagnosis3_desc',
       'diagnosis4_desc', 'diagnosis5_desc', 'diagnosis6_desc',
       'diagnosis7_desc', 'diagnosis8_desc', 'diagnosis9_desc',
       'diagnosis1a_desc', 'DSCPT', 'Diagnosis', 'Orig_diag'],
      dtype='object')

In [19]:
dg_desc['ChargeDate'] = pd.to_datetime(dg_desc['ChargeDate'], errors=("coerce"))

In [20]:
#We want to replace october, november and december 2024 to january 2025
month_to_change = [10,11,12]
mask = (dg_desc['ChargeDate'].dt.year == 2024)&(dg_desc['ChargeDate'].dt.month.isin(month_to_change))
dg_desc.loc[mask,'ChargeDate'] = dg_desc.loc[mask,'ChargeDate'].apply(lambda d: d.replace(year = 2025, month = 1))

In [21]:
dg_desc["charge_m_y"] = dg_desc['ChargeDate'].dt.strftime("%B-%Y")

In [21]:
dg_desc

,DocumentNo,final_encounter_nr,diagnosis1,diagnosis2,diagnosis3,diagnosis4,diagnosis5,diagnosis6,diagnosis7,diagnosis8,...,diagnosis5_desc,diagnosis6_desc,diagnosis7_desc,diagnosis8_desc,diagnosis9_desc,diagnosis1a_desc,DSCPT,Diagnosis,Orig_diag,charge_m_y
0,MHOPB061261364/25,101801231033,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,,0,0,June-2025
1,MHOPB031193989/25,102212104011,V49.5,R07.4,R10.3,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Passenger of car injured in collision with oth...,V49.5-R07.4-R10.3,"V49.5,R07.4,R10.3",March-2025
2,MHOPB031193989/25,102212104011,V49.5,R07.4,R10.3,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Passenger of car injured in collision with oth...,V49.5-R07.4-R10.3,"V49.5,R07.4,R10.3",March-2025
3,MHOPB031193989/25,102212104011,V49.5,R07.4,R10.3,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Passenger of car injured in collision with oth...,V49.5-R07.4-R10.3,"V49.5,R07.4,R10.3",March-2025
4,MHOPB031193989/25,102212104011,V49.5,R07.4,R10.3,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Passenger of car injured in collision with oth...,V49.5-R07.4-R10.3,"V49.5,R07.4,R10.3",March-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771264,WAOPB06156271/25,122506301004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,,,,June-2025
771265,WAOPB06156309/25,122506301017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,,,,June-2025
771266,WAOPB06156316/25,122506304039,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,,,,June-2025
771267,WAOPB06156336/25,122506301022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,,,,June-2025
771268,WAOPB06156346/25,122506301027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,,,,June-2025

In [22]:
dg_desc['charge_m_y'].unique()

array(['June-2025', 'March-2025', 'April-2025', 'January-2025',
       'May-2025', 'February-2025', 'July-2025', nan], dtype=object)

In [23]:
dg_desc.columns

Index(['DocumentNo', 'final_encounter_nr', 'diagnosis1', 'diagnosis2',
       'diagnosis3', 'diagnosis4', 'diagnosis5', 'diagnosis6', 'diagnosis7',
       'diagnosis8', 'diagnosis9', 'diagnosis1a', 'Location', 'Service',
       'ConsultingDoctor', 'ItemName', 'TotalAmount', 'modify_id', 'create_id',
       'ChargeDate', 'diagnosis1_desc', 'diagnosis2_desc', 'diagnosis3_desc',
       'diagnosis4_desc', 'diagnosis5_desc', 'diagnosis6_desc',
       'diagnosis7_desc', 'diagnosis8_desc', 'diagnosis9_desc',
       'diagnosis1a_desc', 'DSCPT', 'Diagnosis', 'Orig_diag', 'charge_m_y'],
      dtype='object')

In [24]:
dig_clean_copy = dg_desc.reindex(columns=['DocumentNo', 'final_encounter_nr','Location', 'Service','ConsultingDoctor', 'ItemName', 'TotalAmount', 'modify_id', 'create_id','Orig_diag','Diagnosis','DSCPT','ChargeDate','charge_m_y'])

In [ ]:
#dig_clean_copy.to_excel(r"C:\Users\user\Downloads\clean_copy.xlsx", sheet_name = "clean_copy")

In [25]:
dig_res1 = dg_desc.reindex(columns=['charge_m_y','Location','final_encounter_nr','Diagnosis','DSCPT','TotalAmount'])

In [26]:
dig_res1["charge_m_y"].unique()

array(['June-2025', 'March-2025', 'April-2025', 'January-2025',
       'May-2025', 'February-2025', 'July-2025', nan], dtype=object)

In [29]:
#oct_24 = dig_clean_copy.loc[(dig_res1["charge_m_y"] == "nan")]
#oct_24

In [27]:
dig_dup  = dig_res1.duplicated()
#dig_dup

In [28]:
dig_res1["TotalAmount"].sum()

5955134571.399999

In [29]:
print(dig_res1[dig_dup].head())

      charge_m_y       Location final_encounter_nr          Diagnosis  \
5     March-2025  Main Hospital       102212104011  V49.5-R07.4-R10.3
6     March-2025  Main Hospital       102212104011  V49.5-R07.4-R10.3
8     April-2025  Main Hospital       102301061421                  0
16  January-2025  Main Hospital       102312051247                  0
29    March-2025  Main Hospital       102403261089                  0

                                                DSCPT  TotalAmount
5   Passenger of car injured in collision with oth...       3000.0
6   Passenger of car injured in collision with oth...       3000.0
8                                                           3000.0
16                                                          1200.0
29                                                          1200.0

In [30]:
dig_res1.columns

Index(['charge_m_y', 'Location', 'final_encounter_nr', 'Diagnosis', 'DSCPT',
       'TotalAmount'],
      dtype='object')

In [31]:
TotalAmount_visit_diag = (
    dig_res1.pivot_table(
        index=['Diagnosis','DSCPT'],
        values='TotalAmount',
        aggfunc=["sum","mean","count"]
    ).reset_index()
)  
TotalAmount_visit_diag

,Diagnosis,DSCPT,sum,mean,count
,,,TotalAmount,TotalAmount,TotalAmount
0,,,1.254318e+07,409.479629,30632
1,0,,4.824027e+09,10885.494866,443161
2,A00,Cholera,5.142000e+03,2571.000000,2
3,A00-A08.0-A08.2,"Cholera,Adenoviral enteritis",3.457200e+04,3457.200000,10
4,A01.0,Typhoid fever,3.864300e+04,2760.214286,14
...,...,...,...,...,...
17982,Z96.5-K05,Presence of tooth-root and mandibular implants...,2.300000e+03,2300.000000,1
17983,Z97.5,Presence of (intrauterine) contraceptive device,1.650030e+05,5500.100000,30
17984,Z98,Other postsurgical states,3.212300e+04,10707.666667,3
17985,Z98.8,Other specified postsurgical states,4.736200e+04,5920.250000,8
17986,Z98.8-S72.4,"Other specified postsurgical states,Fracture o...",2.550000e+03,2550.000000,1

In [32]:
TotalAmount_visit_diag_loc = (
    dig_res1.pivot_table(
        index=['Location','Diagnosis','DSCPT'],
        values='TotalAmount',
        aggfunc=["sum","mean","count"]
    ).reset_index()
)  
TotalAmount_visit_diag_loc

,Location,Diagnosis,DSCPT,sum,mean,count
,,,,TotalAmount,TotalAmount,TotalAmount
0,Anderson,,,3101916.0,572.731905,5416
1,Anderson,0,,159893407.0,6372.794221,25090
2,Anderson,A06-B98.0-I10,"Amoebiasis,Helicobacter pylori [H.pylori] as t...",6593.0,3296.500000,2
3,Anderson,A08.3,Other viral enteritis,17325.0,2475.000000,7
4,Anderson,A09,Other gastroenteritis and colitis of infectiou...,244262.0,3592.088235,68
...,...,...,...,...,...,...
25318,Warwick,Z76.0-N34.1,"Issue of repeat prescription,Nonspecific ureth...",40796.0,10199.000000,4
25319,Warwick,Z76.0-Z71.2-M10-G99.0,"Issue of repeat prescription,Person consulting...",19102.0,19102.000000,1
25320,Warwick,Z87.4,Personal history of diseases of the genitourin...,5500.0,2750.000000,2
25321,Warwick,Z88.0,Personal history of allergy to penicillin,7086.0,3543.000000,2
25322,Warwick,Z97.5,Presence of (intrauterine) contraceptive device,35100.0,4387.500000,8

In [33]:
TotalAmount_visit_diag_loc["Location"].unique()

array(['Anderson', 'Capital', 'Galleria', 'Kiambu', 'Main Hospital',
       'Rosslyn', 'Southfield', 'Warwick'], dtype=object)

In [34]:
anderson = TotalAmount_visit_diag_loc.loc[(TotalAmount_visit_diag_loc['Location']=="Anderson")]
capital = TotalAmount_visit_diag_loc.loc[(TotalAmount_visit_diag_loc['Location']=='Capital')]
galleria = TotalAmount_visit_diag_loc.loc[(TotalAmount_visit_diag_loc['Location']=='Galleria')]
kiambu = TotalAmount_visit_diag_loc.loc[(TotalAmount_visit_diag_loc['Location']=='Kiambu')]
mh = TotalAmount_visit_diag_loc.loc[(TotalAmount_visit_diag_loc['Location']=='Main Hospital')]
rosslyn = TotalAmount_visit_diag_loc.loc[(TotalAmount_visit_diag_loc['Location']=='Rosslyn')]
southfield = TotalAmount_visit_diag_loc.loc[(TotalAmount_visit_diag_loc['Location']=='Southfield')]
warwick = TotalAmount_visit_diag_loc.loc[(TotalAmount_visit_diag_loc['Location']=='Warwick')]

In [40]:
anderson['sum', 'TotalAmount'].sum()

385689504.0

In [41]:
capital['sum', 'TotalAmount'].sum()

117153461.0

In [42]:
galleria['sum', 'TotalAmount'].sum()

214531253.0

In [43]:
kiambu['sum', 'TotalAmount'].sum()

65338506.0

In [44]:
mh['sum', 'TotalAmount'].sum()

4837721149.4

In [1]:
mh

NameError: name 'mh' is not defined

In [45]:
rosslyn['sum', 'TotalAmount'].sum()

67836087.0

In [46]:
southfield['sum', 'TotalAmount'].sum()

99248681.0

In [47]:
warwick['sum', 'TotalAmount'].sum()

167615930.0

In [49]:
with pd.ExcelWriter(r"C:\Users\user\Downloads\TVD_location.xlsx",engine="openpyxl") as dg:
    anderson.to_excel(dg,sheet_name="anderson")
    capital.to_excel(dg,sheet_name="capital")
    galleria.to_excel(dg,sheet_name="galleria")
    kiambu.to_excel(dg,sheet_name='Kiambu')
    mh.to_excel(dg,sheet_name='Main Hospital')
    kiambu.to_excel(dg,sheet_name="galleria")
    southfield.to_excel(dg,sheet_name="southfield" )
    warwick.to_excel(dg,sheet_name="warwick" )

In [45]:
TotalAmount_visit_diag_loc.to_excel(r"C:\Users\user\Downloads\Tavdl.xlsx")

In [35]:
rosslyn.to_excel(r"C:\Users\user\Downloads\roslyn.xlsx")

In [33]:
TotalAmount_visit_diag_location = (
    dig_res1.pivot_table(
        index=['Diagnosis','DSCPT'],
        columns= 'Location',
        values='TotalAmount',
        aggfunc=["sum","mean","count"]
    ).reset_index()
)  
TotalAmount_visit_diag_location

                Diagnosis                                              DSCPT  \
Location
0
1                       0
2                     A00                                            Cholera
3         A00-A08.0-A08.2                       Cholera,Adenoviral enteritis
4                   A01.0                                      Typhoid fever
...                   ...                                                ...
17982           Z96.5-K05  Presence of tooth-root and mandibular implants...
17983               Z97.5    Presence of (intrauterine) contraceptive device
17984                 Z98                          Other postsurgical states
17985               Z98.8                Other specified postsurgical states
17986         Z98.8-S72.4  Other specified postsurgical states,Fracture o...

                  sum                                                   \
Location     Anderson     Capital    Galleria     Kiambu Main Hospital
0           3101916.0    423664.0   1154098.0   394880.0  6.318517e+06
1         159893407.0  25172868.0  73471590.0  9116966.0  4.457496e+09
2                 NaN         NaN         NaN        NaN           NaN
3                 NaN         NaN         NaN        NaN  3.457200e+04
4                 NaN         NaN         NaN        NaN  3.864300e+04
...               ...         ...         ...        ...           ...
17982             NaN         NaN         NaN        NaN  2.300000e+03
17983         74203.0         NaN         NaN     9300.0  2.300000e+03
17984             NaN         NaN         NaN        NaN  2.291000e+04
17985         17062.0         NaN         NaN        NaN  3.030000e+04
17986          2550.0         NaN         NaN        NaN           NaN

                                              ...         mean               \
Location     Rosslyn  Southfield     Warwick  ...   Southfield      Warwick
0           452933.0    571433.0    125739.0  ...   503.909171    97.775272
1         17326033.0  16392070.0  65157933.0  ...  5119.322299  5827.037471
2                NaN      5142.0         NaN  ...  2571.000000          NaN
3                NaN         NaN         NaN  ...          NaN          NaN
4                NaN         NaN         NaN  ...          NaN          NaN
...              ...         ...         ...  ...          ...          ...
17982            NaN         NaN         NaN  ...          NaN          NaN
17983            NaN     44100.0     35100.0  ...  5512.500000  4387.500000
17984            NaN      9213.0         NaN  ...  4606.500000          NaN
17985            NaN         NaN         NaN  ...          NaN          NaN
17986            NaN         NaN         NaN  ...          NaN          NaN

            count                                                            \
Location Anderson Capital Galleria  Kiambu Main Hospital Rosslyn Southfield
0          5416.0  1299.0   2773.0   815.0       17194.0   715.0     1134.0
1         25090.0  4299.0  12391.0  1819.0      381679.0  3499.0     3202.0
2             NaN     NaN      NaN     NaN           NaN     NaN        2.0
3             NaN     NaN      NaN     NaN          10.0     NaN        NaN
4             NaN     NaN      NaN     NaN          14.0     NaN        NaN
...           ...     ...      ...     ...           ...     ...        ...
17982         NaN     NaN      NaN     NaN           1.0     NaN        NaN
17983        11.0     NaN      NaN     2.0           1.0     NaN        8.0
17984         NaN     NaN      NaN     NaN           1.0     NaN        2.0
17985         4.0     NaN      NaN     NaN           4.0     NaN        NaN
17986         1.0     NaN      NaN     NaN           NaN     NaN        NaN


Location  Warwick
0          1286.0
1         11182.0
2             NaN
3             NaN
4             NaN
...           ...
17982         NaN
17983         8.0
17984         NaN
17985         NaN
17986         NaN

[17987 rows x 26 columns]

In [34]:
TotalAmount_visit_diag_location_rowise = (
    dig_res1.pivot_table(
        index=['Location','Diagnosis','DSCPT'],
        values='TotalAmount',
        aggfunc=["sum","mean","count"]
    ).reset_index()
)  
TotalAmount_visit_diag_location_rowise

,Location,Diagnosis,DSCPT,sum,mean,count
,,,,TotalAmount,TotalAmount,TotalAmount
0,Anderson,,,3101916.0,572.731905,5416
1,Anderson,0,,159893407.0,6372.794221,25090
2,Anderson,A06-B98.0-I10,"Amoebiasis,Helicobacter pylori [H.pylori] as t...",6593.0,3296.500000,2
3,Anderson,A08.3,Other viral enteritis,17325.0,2475.000000,7
4,Anderson,A09,Other gastroenteritis and colitis of infectiou...,244262.0,3592.088235,68
...,...,...,...,...,...,...
25318,Warwick,Z76.0-N34.1,"Issue of repeat prescription,Nonspecific ureth...",40796.0,10199.000000,4
25319,Warwick,Z76.0-Z71.2-M10-G99.0,"Issue of repeat prescription,Person consulting...",19102.0,19102.000000,1
25320,Warwick,Z87.4,Personal history of diseases of the genitourin...,5500.0,2750.000000,2
25321,Warwick,Z88.0,Personal history of allergy to penicillin,7086.0,3543.000000,2
25322,Warwick,Z97.5,Presence of (intrauterine) contraceptive device,35100.0,4387.500000,8

In [40]:
TotalAmount_visit_diag_location_rowise.to_excel(r"C:\Users\user\Downloads\clean_copy.xlsx", sheet_name = "Tvlr")

In [41]:
TotalAmount_visit_diag_location_rowise_enc = (
    dig_res1.pivot_table(
        index=['Location','final_encounter_nr','Diagnosis','DSCPT'],
        values='TotalAmount',
        aggfunc=["sum","mean","count"]
    ).reset_index()
)  
TotalAmount_visit_diag_location_rowise_enc

,Location,final_encounter_nr,Diagnosis,DSCPT,sum,mean,count
,,,,,TotalAmount,TotalAmount,TotalAmount
0,Anderson,142309161026,0,,6906.0,3453.0,2
1,Anderson,142402024084,R05-A09.9-K02.9,"Cough,Gastroenteritis and colitis of unspecifi...",3008.0,3008.0,1
2,Anderson,142402164167,,,812.0,812.0,1
3,Anderson,142402174039,R05-R51,"Cough,Headache",3489.0,1163.0,3
4,Anderson,142403214165,R22.3-M79.6,"Localised swelling, mass and lump, upper limb,...",2300.0,2300.0,1
...,...,...,...,...,...,...,...
211082,Warwick,122506304056,J00,Acute nasopharyngitis [common cold],5964.0,1988.0,3
211083,Warwick,122506304057,J00,Acute nasopharyngitis [common cold],6159.0,2053.0,3
211084,Warwick,122506304058,N50.8-R30-Z00.0,Other specified disorders of male genital orga...,33270.0,5545.0,6
211085,Warwick,122506304059,Z00.0-R30,"General medical examination,Pain associated wi...",26700.0,6675.0,4
211086,Warwick,122506304060,S51,Open wound of forearm,6000.0,3000.0,2

In [43]:
TotalAmount_visit_diag_location_rowise_enc.to_excel(r"C:\Users\user\Downloads\tvlre.xlsx", sheet_name = "Tvlre")

In [35]:
TAmount_visitId_diagnosis = (
    dig_res1.pivot_table(
        index= ['final_encounter_nr','Diagnosis', 'DSCPT'],
        values='TotalAmount',
        aggfunc=["sum","count","mean"]
    ).reset_index()
)
TAmount_visitId_diagnosis.head(10)

,final_encounter_nr,Diagnosis,DSCPT,sum,count,mean
,,,,TotalAmount,TotalAmount,TotalAmount
0,101801231033,0,,7100.0,1,7100.000000
1,102212104011,V49.5-R07.4-R10.3,Passenger of car injured in collision with oth...,13669.0,6,2278.166667
2,102301061421,0,,6000.0,2,3000.000000
3,102309254116,R22.4,"Localised swelling, mass and lump, lower limb",2300.0,1,2300.000000
4,102312051247,0,,33640.0,10,3364.000000
5,102403024120,R63.4,Abnormal weight loss,2300.0,1,2300.000000
6,102403054214,,,250.0,1,250.000000
7,102403171067,0,,53000.0,3,17666.666667
8,102403214262,N39.0,"Urinary tract infection, site not specified",10880.0,2,5440.000000
9,102403261089,0,,73310.0,15,4887.333333

In [38]:
TAmount_visitId_diagnosis_location = (
    dig_res1.pivot_table(
        index= ['final_encounter_nr','Diagnosis', 'DSCPT'],
        columns= 'Location',
        values='TotalAmount',
        aggfunc=["sum","count","mean"]
    ).reset_index()
)
TAmount_visitId_diagnosis_location

         final_encounter_nr          Diagnosis  \
Location
0              101801231033                  0
1              102212104011  V49.5-R07.4-R10.3
2              102301061421                  0
3              102309254116              R22.4
4              102312051247                  0
...                     ...                ...
210782         172506304049              K29.7
210783         172506304051              D23.4
210784         172506304052                R51
210785         172506304053              J03.9
210786         172506304055              Z71.2

                                                      DSCPT      sum          \
Location                                                    Anderson Capital
0                                                                NaN     NaN
1         Passenger of car injured in collision with oth...      NaN     NaN
2                                                                NaN     NaN
3             Localised swelling, mass and lump, lower limb      NaN     NaN
4                                                                NaN     NaN
...                                                     ...      ...     ...
210782                               Gastritis, unspecified      NaN     NaN
210783              Benign neoplasm, skin of scalp and neck      NaN     NaN
210784                                             Headache      NaN     NaN
210785                       Acute tonsillitis, unspecified      NaN     NaN
210786    Person consulting for explanation of investiga...      NaN     NaN

                                                             ...      count  \
Location Galleria   Kiambu Main Hospital Rosslyn Southfield  ... Southfield
0             NaN      NaN        7100.0     NaN        NaN  ...        NaN
1             NaN      NaN       13669.0     NaN        NaN  ...        NaN
2             NaN      NaN        6000.0     NaN        NaN  ...        NaN
3             NaN      NaN        2300.0     NaN        NaN  ...        NaN
4             NaN      NaN       33640.0     NaN        NaN  ...        NaN
...           ...      ...           ...     ...        ...  ...        ...
210782        NaN  10910.0           NaN     NaN        NaN  ...        NaN
210783        NaN   4037.0           NaN     NaN        NaN  ...        NaN
210784        NaN   5859.0           NaN     NaN        NaN  ...        NaN
210785        NaN   6511.0           NaN     NaN        NaN  ...        NaN
210786        NaN   4436.0           NaN     NaN        NaN  ...        NaN

                     mean                                                 \
Location Warwick Anderson Capital Galleria  Kiambu Main Hospital Rosslyn
0            NaN      NaN     NaN      NaN     NaN   7100.000000     NaN
1            NaN      NaN     NaN      NaN     NaN   2278.166667     NaN
2            NaN      NaN     NaN      NaN     NaN   3000.000000     NaN
3            NaN      NaN     NaN      NaN     NaN   2300.000000     NaN
4            NaN      NaN     NaN      NaN     NaN   3364.000000     NaN
...          ...      ...     ...      ...     ...           ...     ...
210782       NaN      NaN     NaN      NaN  2182.0           NaN     NaN
210783       NaN      NaN     NaN      NaN  2018.5           NaN     NaN
210784       NaN      NaN     NaN      NaN  2929.5           NaN     NaN
210785       NaN      NaN     NaN      NaN  3255.5           NaN     NaN
210786       NaN      NaN     NaN      NaN  2218.0           NaN     NaN


Location Southfield Warwick
0               NaN     NaN
1               NaN     NaN
2               NaN     NaN
3               NaN     NaN
4               NaN     NaN
...             ...     ...
210782          NaN     NaN
210783          NaN     NaN
210784          NaN     NaN
210785          NaN     NaN
210786          NaN     NaN

[210787 rows x 27 columns]

In [39]:
with pd.ExcelWriter(r"C:\Users\user\Downloads\diagnosis_analysis.xlsx",engine="openpyxl") as dg:
    TotalAmount_visit_diag.to_excel(dg,sheet_name="Total_amount_visit_diag")
    TotalAmount_visit_diag_location.to_excel(dg,sheet_name="TotalAmount_visit_diag_location")
    TotalAmount_visit_diag_location_rowise.to_excel(dg,sheet_name="TotalAmount_visit_diag_location_rowise")
    TAmount_visitId_diagnosis_location.to_excel(dg,sheet_name="TAmount_visitId_diagnosis_location")

c:\ProgramData\anaconda3\Lib\site-packages\openpyxl\workbook\child.py:99: UserWarning: Title is more than 31 characters. Some applications may not be able to read the file
  warnings.warn("Title is more than 31 characters. Some applications may not be able to read the file")